- name: Add A record for backup
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ startup_name }}."
    record: "backup.{{ startup_name }}."
    value: "{{ backup_server_ip }}"
    type: "A"
  when: inventory_hostname is in groups['dns_primary'][0]
  notify: Restart bind9

- name: Add an CNAME record for backup
  nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ startup_name }}."
    record: "{{ item['cname'] }}.{{ startup_name }}."
    value: "{{ item['machine'] }}.{{ startup_name }}."
    type: "CNAME"
  loop: "{{ cnames }}"
  when: inventory_hostname in groups['dns_primary'][0]
  notify: Restart bind9