- name: Create grafana directories
  ansible.builtin.file:
    path: /opt/grafana/provisioning/{{ item }}
    state: directory
  loop:
    - dashboards
    - datasources

- name: Copy grafana.ini
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini 
  no_log: true
  notify: Restart grafana

- name: Copy sample_datasource.yaml
  ansible.builtin.template:
    src: sample_datasource.yaml.j2
    dest: /opt/grafana/provisioning/datasources/default.yaml
  notify: Restart grafana

- name: Copy sample_dashboard.yaml
  ansible.builtin.template:
    src: sample_dashboard.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/default.yaml
  notify: Restart grafana

- name: Copy json files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
  loop:
    - main.json
    - mysql.json
    - syslog.json
  notify: Restart grafana

- name: Create Grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"
    restart_policy: always