- name: Install uWSGI packages
  ansible.builtin.apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3
    
- name: Copy agama.ini
  ansible.builtin.template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: 0600
  no_log: true
  notify:
    - Restart uWSGI
    
- name: uWSGI service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: true
