- name: Install bind9
  ansible.builtin.apt:
    name: bind9
    state: present

- name: Copy named.conf.options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify:
    - Restart bind9

- name: Copy named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
    - Restart bind9

- name: Copy db.j2
  ansible.builtin.template:
    src: db.j2
    dest: /var/lib/bind/db.{{ startup_name }}
  notify:
    - Restart bind9

- name: bind9 service
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true

#- name: Collect variables
#  ansible.builtin.setup:

#- name: Print variables
#  ansible.builtin.debug:
#    var: hostvars[{{ vm1 }}]