- name: Create a directory /opt/agama
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Download agama.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}
    dest: /opt/agama/
  loop:
    - agama.py
    - Dockerfile

- name: Build Agama Docker image
  community.docker.docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: Start Agama Docker container 
  community.docker.docker_container:
    name: agama-{{ item|int +1 }}
    image: agama
    env: 
      AGAMA_DATABASE_URI: mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{ mysql_host }}/{{mysql_database}}
    state: started
    published_ports: 
      - "{{ agama_port + item|int }}:8000"
    restart_policy: always
  no_log: true
  loop: "{{ range(agama_quantity) | list}}"