- name: Install mysql-server
  ansible.builtin.apt:
    name: mysql-server
    state: present
   
- name: Copy override.cnf
  ansible.builtin.copy:
    src: override
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify:
    - Restart mysql

- name: mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Copy .my.cnf for prometheus-mysqld-exporter
  ansible.builtin.template:
    src: my.cnf.promexp.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    mode: 0600
  no_log: true
  notify:
    - Restart prometheus-mysqld-exporter

- name: Create a directory for mysql backup
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    mode: '0700'
    
- name: Copy .my.cnf for backup user
  ansible.builtin.template:
    src: my.cnf.backup.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: 0400
  notify: Restart mysql

- name: Copy cron tab 
  ansible.builtin.template:
    src: cron_tab.j2
    dest: /etc/cron.d/mysql-backup

- name: Install python3-pymysql
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: Install prometheus-mysqld-exporter
  ansible.builtin.apt: 
    name: prometheus-mysqld-exporter
    state: present
    
- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"

- name: MySQL exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_export }}"
    password: "{{ mysql_export_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: prometheus-mysqld-exporter service
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true

- name: MySQL backup user
  community.mysql.mysql_user:
    name: "{{ mysql_backup }}"
    password: "{{ mysql_backup_password }}"
    priv: "*.*:LOCK TABLES,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock