- name: Install mysql-server
  ansible.builtin.apt:
    name: mysql-server
    state: present
   
- name: Copy override.cnf
  ansible.builtin.copy:
    src: override
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify:
    - Restart mysql

- name: mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
    
- name: Install python3-pymysql
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
    
- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
