- name: Install mysql-server
  ansible.builtin.apt:
    name: mysql-server
    state: present
   
- name: Copy override.cnf
  ansible.builtin.copy:
    src: override
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify:
    - Restart mysql

- name: mysql service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Copy .my.cnf
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    mode: 0600
  no_log: true
  notify:
    - Restart prometheus-mysqld-exporter
    
- name: Install python3-pymysql
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: Install prometheus-mysqld-exporter
  ansible.builtin.apt: 
    name: prometheus-mysqld-exporter
    state: present
    
- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"

- name: MySQL exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_export }}"
    password: "{{ mysql_export_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: prometheus-mysqld-exporter service
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: true