- name: Restart influxdb
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: Restart influxdb_stats_exporter
  ansible.builtin.service:
    name: prometheus-influxdb-stats-exporter
    state: restarted
    enabled: yes

- name: Restart influxdb_stats_exporter daemon
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: prometheus-influxdb-stats-exporter