- name: Install prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Copy prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: 
    - Restart prometheus

- name: Copy prometheus
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: 
    - Restart prometheus

- name: Prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true