#- name: Ansible ping module
#  ansible.builtin.ping:

- name: Add the user 'juri'
  ansible.builtin.user:
    name: juri
    comment: Juri Hudolejev
    
- name: Add the user 'roman'
  ansible.builtin.user:
    name: roman
    comment: Roman Kuchin
    
- name: Set key for juri
  ansible.posix.authorized_key:
    user: juri
    state: present
    key: https://github.com/hudolejev.keys

- name: Set key for roman
  ansible.posix.authorized_key:
    user: roman
    state: present
    key: https://github.com/romankuchin.keys
    
- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
