#- name: Ansible ping module
#  ansible.builtin.ping:

#- name: Add the user 'juri'
#  ansible.builtin.user:
#    name: juri
#    comment: Juri Hudolejev
    
#- name: Add the user 'roman'
#  ansible.builtin.user:
#    name: roman
#    comment: Roman Kuchin
    
#- name: Set key for juri
#  ansible.posix.authorized_key:
#    user: juri
#    state: present
#    key: https://github.com/hudolejev.keys

#- name: Set key for roman
#  ansible.posix.authorized_key:
#    user: roman
#    state: present
#    key: https://github.com/romankuchin.keys

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Install prometheus node exporters
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Install up-to-date CA certificates
  ansible.builtin.apt:
    name: ca-certificates=20230311ubuntu0.20.04.1
    state: present

- name: Copy tel.conf for rsyslog
  ansible.builtin.template:
    src: tel.conf.j2
    dest: /etc/rsyslog.d/tel.conf
  notify: 
    - Restart rsyslog

- name: rsyslog service
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true

- name: Add the user 'backup'
  ansible.builtin.user:
    name: backup
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Copy known_hosts
  ansible.builtin.template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup